### ISSUE TITLE
working on User signup and login

### ISSUE THREAD

**Issue by Seshagiri9398** [Event-Coordination-Engine/seshagiri-ece#2]
1.create a User signup
2.validation of user signup
3.Work on Users Login API
4.Encrypting Password while moving to database

**Comment by Seshagiri9398** [comment]
user columns modify :[commit link](https://github.com/Event-Coordination-Engine/seshagiri-ece/commit/aca3ce065b46103938f7fa6d1c1feb78d4cd7269)

**Comment by Seshagiri9398** [comment]
user signup and few validations : [commit link](https://github.com/Event-Coordination-Engine/seshagiri-ece/commit/21b7aa0b936be74f7e1471b89ff54eced4c4cc3d#diff-f1cd7d9737dc25462a51fa2a85b76503d88a631873560c17dc840a8332bd4fd7)

**Comment by yateesh-chandra-duggirala** [comment]
Good Work @Seshagiri9398 
This was what I was expecting from everyone..


![Image](https://github.com/user-attachments/assets/50f72a13-67ff-4cd7-aa6e-d437e3dfd6cc)

**Comment by Seshagiri9398** [comment]
user_login successfully : [commit](https://github.com/Event-Coordination-Engine/seshagiri-ece/commit/57e14afe688dfb6bbffaa29f2769f4c265064ceb#diff-f1cd7d9737dc25462a51fa2a85b76503d88a631873560c17dc840a8332bd4fd7)
